# you can delete this line if you're not using a specific Docker image
# get more information at https://hub.docker.com/r/rocker/verse/
image: rocker/verse:3.4.4

# order of the different jobs
stages:
  - build
  - document
  - check
  - test
  - deploy

# define system environment variables
variables:
  R_REPOS: "http://cloud.R-project.org/"
  R_LIBS : "$CI_PROJECT_DIR/install_deps" # dependencies cache
  R_ENVIRON : "$CI_PROJECT_DIR/.Renviron" # R environment cache
  R_TMP_USER: "$CI_PROJECT_DIR/tmp"  # temporary directory

# Cache R directories in between jobs
cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - $R_LIBS
      - $R_ENVIRON


# create an archive 
buildBinary:
  when: manual
  stage: build
  before_script:
   - mkdir -p $R_LIBS
   - echo 'R_LIBS_USER="$R_LIBS"' > .Renviron
   - R -e '.libPaths()'
   - R -e 'devtools::install_deps(dep = TRUE,lib = Sys.getenv("R_LIBS"), upgrade = FALSE)'
  script:
   - R -e 'devtools::build(binary = TRUE)'

checkErrors:
  stage: check
  script:
    - mkdir -p $R_TMP_USER
    - R -e 'tryCatch(if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["errors"]], character(0))) system("mkdir -p $R_TMP_USER;touch $R_TMP_USER/errorsFail"), error = function(e) system("touch $R_TMP_USER/errorsFail"))'
    - if [ -f $R_TMP_USER/errorsFail ]; then echo "Check Errors"; exit 1 ; else echo "No Errors"; fi

checkWarnings:
  allow_failure: true
  stage: check
  script:
    - mkdir -p $R_TMP_USER
    - R -e 'tryCatch(if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["warnings"]], character(0))) system("mkdir -p $R_TMP_USER;touch $R_TMP_USER/warningsFail"), error = function(e) system("touch $R_TMP_USER/warningsFail"))'
    - if [ -f $R_TMP_USER/warningsFail ]; then echo "Check Warnings"; exit 1 ; else echo "No Warnings"; fi

checkNotes:
  allow_failure: true
  stage: check
  script:
    - mkdir -p $R_TMP_USER
    - R -e 'tryCatch(if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["notes"]], character(0))) system("mkdir -p $R_TMP_USER;touch $R_TMP_USER/notesFail"), error = function(e) system("touch $R_TMP_USER/warningsFail"))'
    - if [ -f $R_TMP_USER/notesFail ]; then echo "Check Notes"; exit 1 ; else echo "No Notes"; fi

unitTests:
  when: manual
  stage: test
  script:
    - mkdir -p $R_TMP_USER
    - R -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) system("touch $R_TMP_USER/testsFail")
    - if [ -f $R_TMP_USER/testsFail ]; then echo "Check Tests"; exit 1 ; else echo "Tests passed"; fi
    
codeCoverage:
  when: manual
  stage: test
  script:
    - R -e 'covr::codecov()'

installFromGithub:
  stage: test
  script:
    - R -e 'source("https://install-github.me/r-lib/desc");desc<-desc::description$new();remotes::install_github("OpenSILEX/phisWSClientR", build_vignettes=TRUE,ref=desc$get("Version")[[1]])'

installLocally:
  stage: test
  script:
    - R -e 'devtools::install(build_vignettes=TRUE)'

deployOnTestRepository:
  when: manual
  stage: build
  script:
    # Install ssh-agent through openssh-client if not present
    - 'which ssh-agent || ( apt-get update -qy && apt-get install openssh-client -qqy )'
    # Add the private key to this user
    - eval $(ssh-agent -s) && ssh-add <(echo "$SSH_PRIVATE_KEY") && mkdir -p /root/.ssh
    # Docker specific settings
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /root/.ssh/config'
    # Config git to avoid first usage questions. Set the identity
    - git config --global user.email "$GITHUB_USER_EMAIL" && git config --global user.name "Gitlab CI"
    # 
    # Do Git stuff, for example:
    #
    - "git remote add upstream https://github.com/niio972/phisWSClientR"
    - "git fetch upstream"
    - "git push upstream HEAD:master --force"
  only:
    - v2.0.0
    
deployOnTestRepositoryTest: 
  image: ilyasemenov/gitlab-ci-git-push
  only: 
    - master
  script: 
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
    - git config --global user.email "$GITHUB_USER_NAME"
    - git config --global user.name "$GITHUB_USER_EMAIL"
    - "mkdir -p ~/.ssh"
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - "git remote add upstream https://github.com/niio972/phisWSClientR"
    - "git fetch upstream"
    - "git push upstream HEAD:master --force"
  stage: deploy
  when: manual
