# order of the different jobs
stages:
  - build
  - check
  - test

# define system environment variables
variables:
  PACKAGE_VERSION: "2.4.1"
  R_REPOS: "http://cloud.R-project.org/"
  R_LIBS_CACHE : "$CI_PROJECT_DIR/.cache/install_deps/$R_VERSION" # dependencies cache
  R_ENVIRON : "$CI_PROJECT_DIR/.Renviron" # R environment cache
  R_TMP_USER: "$CI_PROJECT_DIR/tmp"  # temporary directory
  R_IMG_LIB: "/usr/local/lib/R/site-library"  # temporary directory
  BUILT_PACKAGE: "$CI_PROJECT_DIR/../phisWSClientR_${PACKAGE_VERSION}_R_x86_64-pc-linux-gnu.tar.gz"  # temporary directory
  BUILT_PACKAGE_DIR: "$CI_PROJECT_DIR/.built"
  BUILT_PACKAGE_PATH: "$CI_PROJECT_DIR/.built/phisWSClientR_${PACKAGE_VERSION}_R_x86_64-pc-linux-gnu.tar.gz"
  SET_R_LIB: '.libPaths(c(Sys.getenv("R_LIBS_CACHE"),.libPaths()))'

# Cache R directories in between jobs
.cache_dependencies: &cache_dependencies
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $R_LIBS_CACHE

.prepare_script_r: &prepare_script_r
  <<: *cache_dependencies
  image: $DOCKER_REGISTRY/opensilex/data-analysis-visualisation/phiswsclientr/r-tidyverse:$IMAGE_TAG
  before_script:
    - if [ -d "$BUILT_PACKAGE_DIR" ]; then rm -R $BUILT_PACKAGE_DIR; fi
    
# create an archive 
.build:binary: &build_r
  <<: *prepare_script_r
  stage: build
  script:
    - R -e 'devtools::build(binary = TRUE)'
    - mkdir -p $BUILT_PACKAGE_DIR
    - cp $BUILT_PACKAGE $BUILT_PACKAGE_DIR
    - chmod -R 777 $BUILT_PACKAGE_PATH
  artifacts:
    paths:
      - $BUILT_PACKAGE_PATH
  rules:
    - if: '$BUILD_IMAGES != "true"'

# create an docker image 
.build:image: &build_image
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - if [ -z "$IMAGE_TAG" ]; then echo "Missing IMAGE_TAG variable"; exit 1; fi 
    - docker info
    - docker build -t $DOCKER_REGISTRY/opensilex/data-analysis-visualisation/phiswsclientr/r-tidyverse  --tag=registry.forgemia.inra.fr/opensilex/data-analysis-visualisation/phiswsclientr/r-tidyverse:$IMAGE_TAG --build-arg R_VERSION=$IMAGE_TAG  .
    - docker push $DOCKER_REGISTRY/opensilex/data-analysis-visualisation/phiswsclientr/r-tidyverse:$IMAGE_TAG
  rules:
    - if: '$BUILD_IMAGES == "true"'

.check:errors: &errors_r
  <<: *prepare_script_r
  stage: check
  script:
    - R -e 'devtools::check(document = FALSE, args = "--no-tests", error_on = c("error"))'
 
.check:warnings: &warnings_r
  <<: *prepare_script_r
  stage: check
  script:
    - R -e 'devtools::check(document = FALSE, args = "--no-tests", error_on = c("warning"))'

.check:notes: &notes_r
  <<: *prepare_script_r
  allow_failure: true
  stage: check
  script:
    - R -e 'devtools::check(document = FALSE, args = "--no-tests", error_on = c("note"))'


.unit:tests: &unit_r
  <<: *prepare_script_r
  when: manual
  stage: test
  script:
    - R -e 'devtools::test(stop_on_failure = TRUE)'


.install:locally: &install_local_r
  <<: *prepare_script_r
  stage: test
  script:
    - R -e 'options(repos =c(CRAN=Sys.getenv("R_REPOS")));devtools::install(build_vignettes=TRUE,dependencies = TRUE)'


.code:coverage: &coverage_r
  <<: *prepare_script_r
  allow_failure: true
  when: manual
  stage: test
  script:
    - R -e 'covr::codecov()'
    
.with_r34: &with_r34
  variables: 
   IMAGE_TAG: "3.4.4"

.with_r35: &with_r35
  variables: 
   IMAGE_TAG: "3.5.3"

.with_r36: &with_r36
  variables: 
   IMAGE_TAG: "3.6.3"

.with_r40: &with_r40
  variables: 
   IMAGE_TAG: "4.0.2"


buildImage:3.4:
  <<: *with_r34
  <<: *build_image

buildImage:3.5:
  <<: *with_r35
  <<: *build_image

buildImage:3.6:
  <<: *with_r36
  <<: *build_image

buildImage:4.0:
  <<: *with_r40
  <<: *build_image

buildBinary:3.4:
  <<: *with_r34
  <<: *build_r
  
checkWarnings:3.4:
  <<: *with_r34
  <<: *warnings_r
  needs:
    - job: "buildBinary:3.4"
    
checkErrors:3.4:
  <<: *with_r34
  <<: *errors_r
  needs:
    - job: "buildBinary:3.4"

checkNotes:3.4:
  <<: *with_r34
  <<: *notes_r
  needs:
    - job: "buildBinary:3.4"

test_unit:3.4:
  <<: *with_r34
  <<: *unit_r
  needs:
    - job: "checkErrors:3.4"
 
install_local:3.4:
  <<: *with_r34
  <<: *install_local_r
  needs:
    - job: "checkErrors:3.4"
 
code_coverage:3.4:
  <<: *with_r34
  <<: *coverage_r
  needs:
    - job: "checkErrors:3.4"
 
buildBinary:3.5:
  <<: *with_r35
  <<: *build_r
  
checkWarnings:3.5:
  <<: *with_r35
  <<: *warnings_r
  needs:
    - job: "buildBinary:3.5"
    
checkErrors:3.5:
  <<: *with_r35
  <<: *errors_r
  needs:
    - job: "buildBinary:3.5"

checkNotes:3.5:
  <<: *with_r35
  <<: *notes_r
  needs:
    - job: "buildBinary:3.5"

test_unit:3.5:
  <<: *with_r35
  <<: *unit_r
  needs:
    - job: "checkErrors:3.5"
 
install_local:3.5:
  <<: *with_r35
  <<: *install_local_r
  needs:
    - job: "checkErrors:3.5"
 
code_coverage:3.5:
  <<: *with_r35
  <<: *coverage_r
  needs:
    - job: "checkErrors:3.5"

buildBinary:3.6:
  <<: *with_r36
  <<: *build_r
  
checkWarnings:3.6:
  <<: *with_r36
  <<: *warnings_r
  needs:
    - job: "buildBinary:3.6"
    
checkErrors:3.6:
  <<: *with_r36
  <<: *errors_r
  needs:
    - job: "buildBinary:3.6"

checkNotes:3.6:
  <<: *with_r36
  <<: *notes_r
  needs:
    - job: "buildBinary:3.6"

test_unit:3.6:
  <<: *with_r36
  <<: *unit_r
  needs:
    - job: "checkErrors:3.6"
 
install_local:3.6:
  <<: *with_r36
  <<: *install_local_r
  needs:
    - job: "checkErrors:3.6"
 
code_coverage:3.6:
  <<: *with_r36
  <<: *coverage_r
  needs:
    - job: "checkErrors:3.6"

buildBinary:4.0:
  <<: *with_r40
  <<: *build_r
  
checkWarnings:4.0:
  <<: *with_r40
  <<: *warnings_r
  needs:
    - job: "buildBinary:4.0"
    
checkErrors:4.0:
  <<: *with_r40
  <<: *errors_r
  needs:
    - job: "buildBinary:4.0"

checkNotes:4.0:
  <<: *with_r40
  <<: *notes_r
  needs:
    - job: "buildBinary:4.0"

test_unit:4.0:
  <<: *with_r40
  <<: *unit_r
  needs:
    - job: "checkErrors:4.0"
 
install_local:4.0:
  <<: *with_r40
  <<: *install_local_r
  needs:
    - job: "checkErrors:4.0"
 
code_coverage:4.0:
  <<: *with_r40
  <<: *coverage_r
  needs:
    - job: "checkErrors:4.0"