# you can delete this line if you're not using Docker
image: debian:9

# install R
before_script:
  - apt update
  - apt install r-base -y

 
after_script:
  - R -e 'install.packages("devtools", repos="http://cloud.r-project.org/")'
  - R -e 'install.packages("remotes", repos="http://cloud.r-project.org/")'
  - R -e 'install.packages("covr", repos="http://cloud.r-project.org/")'
  
build1:
  stage: build
  script:
    - R -e 'devtools::build()'

install_from_github:
  stage: test
  script:
    - R -e 'remotes::install_github("OpenSILEX/phisWSClientR", build_vignettes=TRUE,ref="v1.3.0",upgrade ="always")'

code_coverage:
  stage: test
  script:
    - echo "Code coverage"
    - R -e  "covr::codecov()"


deploy1:
  stage: deploy
  script:
    - git remote add upstream https://github.com/niio972/phisWSClientR
    - git fetch upstream
    - git push upstream master
  when: manual
  only:
    - master
