# you can delete this line if you're not using Docker
image: r-base

stages:
  - build
  - document
  - check
  - test
  - deploy


variables:
  R_REPOS: "http://cloud.R-project.org/"

# install R and http dependencies
before_script:
   - apt-get update
   - apt-get install libssl-dev libcurl4-openssl-dev libgit2-dev -y
   - R -e 'install.packages("devtools", repos="http://cloud.R-project.org/")'
   - R -e 'install.packages("remotes", repos="http://cloud.R-project.org/")'
   - R -e 'install.packages("covr", repos="http://cloud.R-project.org/")'
   - R -e 'install.packages("knitr", repos="http://cloud.R-project.org/")'
   - R -e 'install.packages("ggplot2", repos="http://cloud.R-project.org/")'
   - R -e 'install.packages("tidyr", repos="http://cloud.R-project.org/")'
   - R -e 'install.packages("dplyr", repos="http://cloud.R-project.org/")'
   - R -e 'install.packages("lubridate", repos="http://cloud.R-project.org/")'
   - R -e 'install.packages("urltools", repos="http://cloud.R-project.org/")'
   
# Cache packages in between jobs
cache:
    paths:
      - /usr/local/lib/R/site-library
      - /var/lib/R
      - /root/R

buildbinary:
  stage: build
  script:
    - R -e 'devtools::build(binary = TRUE)'

checkerrors:
  stage: check
  script:
    - R -e 'try(if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["errors"]], character(0))) stop("Check with Errors"), silent = TRUE)'

checkwarnings:
  stage: check
  script:
    - R -e 'try(if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["warnings"]], character(0))) stop("Check with Warnings"), silent = TRUE)'

checknotes:
  stage: check
  script:
    - R -e 'try(if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["notes"]], character(0))) stop("Check with Notes"), silent = TRUE)'

unittests:
  stage: test
  script:
    - R -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'

codecov:
  stage: test
  script:
    - R -e 'covr::codecov()'

install_from_github:
  stage: deploy
  script:
    - R -e 'remotes::install_github("OpenSILEX/phisWSClientR", build_vignettes=TRUE,ref="v1.3.0",upgrade ="always")'

install:
  stage: deploy
  script:
    - R -e 'devtools::install()'

deployonotherrepository:
  stage: deploy
  script:
    - git remote add upstream https://github.com/niio972/phisWSClientR
    - git fetch upstream
    - git push upstream master
  when: manual
  only:
    - master
